[package]
name = "xtask_kompari"
version = "0.1.0"
edition = "2021"

[dependencies]
demolib = { path = "../demolib" }
clap = { version = "4.5", features = ["derive"] }
kompari = { path = "../../kompari" }
kompari-tasks = { path = "../../kompari-tasks" }
